### ISSUE TITLE
`runtests.mpi.MPITestFixture` are skipped when running with pytest

### ISSUE THREAD

**Issue by AntoineSIMTEK** [IMTEK-Simulation/NuMPI#17]
This is not a problem if we decide to not test with pytest when mpi4py is here. All single processor tests are run with `python run-test.py`. 

When `mpi4py` is not here all tests are run normally because we use a self-written fixture.

**Comment by pastewka** [comment]
I don't think this is a problem. It is important that the CI tests runs in parallel, but they should.

**Comment by AntoineSIMTEK** [comment]
So do we remove `pytest` from the CI MPI case ?
