### ISSUE TITLE
test_FileSave_2D stalls on MPI-parallel CI

### ISSUE THREAD

**Issue by pastewka** [IMTEK-Simulation/NuMPI#19]
Output:
```build/testenv/lib/python3.6/site-packages/tests/test_io.py::test_FileSave_2D[3-make_2d_slab_y] FAILED```
and then times out, the code does not appear to quit.

See here:
https://www.travis-ci.org/IMTEK-Simulation/NuMPI/jobs/534365398

**Comment by AntoineSIMTEK** [comment]
Closed by b49ab198a8854c03b1580ee6b7c9b653aec97c9f
