### ISSUE TITLE
save_npy works only for two-dimensional arrays

### ISSUE THREAD

**Issue by pastewka** [IMTEK-Simulation/NuMPI#20]
Presently, `save_npy` works only for two-dimensional array. It should at least also work for one-dimensional ones and be able to accepts lists. Examples:

```python
v = [1,2,3]
save_npy('test.npy', v, comm=comm)
```

**Comment by AntoineSIMTEK** [comment]
Closed by 8ada477fe56f7494be356ab18d91349bdd27c6c1
