### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by pastewka** [IMTEK-Simulation/NuMPI#5]
The code currently does not follow pep-8 and has other issues:

- [x] Strict pep-8.
- [x] License headers with copyright information. Need an automatic tool to generate this.
- [x] Turn french into english language comments.
- [x] Write proper README.md.
- [x] File names should not have underscores.

**Comment by AntoineSIMTEK** [comment]
I have to rename `MPI_LBFGS_Matrix_H.py` and we are done. I guess that the no underscores rule only holds inside the module ?

**Comment by pastewka** [comment]
Yes. For tests underscores are fine.

**Comment by pastewka** [comment]
Closes with #2916068
